version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - uploads:/app/uploads
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - LIBRETRANSLATE_URL=http://big_bear_libretranslate:5000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  libretranslate:
    container_name: big_bear_libretranslate
    image: libretranslate/libretranslate:v1.3.9
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - LT_API_KEYS=false
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,tr
    volumes:
      - libretranslate_models:/home/libretranslate/.local
    networks:
      - backend-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
  uploads:
  pgadmin:
  libretranslate_models:
    driver: local
