version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - postgres
      - libretranslate
    networks:
      - backend-network

  postgres:
    image: postgres:16
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - 5000:5000
    environment:
      - LT_LOAD_ONLY=en,tr
      - LT_DISABLE_WEB_UI=true
      - LT_DISABLE_FILES_TRANSLATION=true
      - LT_DISABLE_TELEMETRY=true
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  uploads:
    driver: local
