@baseUrl = http://localhost:3000
@auth_token =   jwt_token
### Auth Endpoints ###

# Kullanıcı Girişi
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "Password123!"
}

### User Endpoints ###

# Kullanıcı Kaydı
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "user@example.com",
    "role": "user",
    "password": "Password123!"
}

# Kullanıcı Bilgilerini Getir
GET {{baseUrl}}/profile
Authorization: Bearer {{auth_token}}

### Word Endpoints ###

# Yeni Kelime Ekle
POST {{baseUrl}}/words
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "originalText": "hello",
    "translatedText": "merhaba",
    "sourceLanguage": "en",
    "targetLanguage": "tr"
}

# Kelimeleri Listele
GET {{baseUrl}}/words
Authorization: Bearer {{auth_token}}

# Kelime Güncelle
PUT {{baseUrl}}/words/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "translatedText": "selam"
}

# Kelime Sil
DELETE {{baseUrl}}/words/1
Authorization: Bearer {{auth_token}}

### Translation Endpoints ###

# Metin Çevirisi
POST {{baseUrl}}/translation/translate
Content-Type: application/json


{
    "text": "hello",
    "sourceLanguage": "en",
    "targetLanguage": "tr"
}

### Book Endpoints ###

# PDF'den Kitap Oluştur
POST {{baseUrl}}/books/upload/pdf
Content-Type: multipart/form-data
Authorization: Bearer {{auth_token}}

file: <PDF_DOSYASI>

# Yeni Kitap Oluştur
POST {{baseUrl}}/books
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title": "Test Book",
    "content": "This is a test book content."
}

# Kitapları Listele
GET {{baseUrl}}/books
Authorization: Bearer {{auth_token}}

# Kitap Detayı
GET {{baseUrl}}/books/1
Authorization: Bearer {{auth_token}}

# Kitap Sil
DELETE {{baseUrl}}/books/1
Authorization: Bearer {{auth_token}}

### File Endpoints ###

# PDF Yükle ve Metin Çıkar
POST {{baseUrl}}/files/upload/pdf
Content-Type: multipart/form-data
Authorization: Bearer {{auth_token}}

file: <PDF_DOSYASI>

### Audio Endpoints ###

# Metin Okuma
POST {{baseUrl}}/audio/text-to-speech
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "text": "Hello world",
    "language": "en"
}

# Ses Dosyası Yükle
POST {{baseUrl}}/audio/upload
Content-Type: multipart/form-data
Authorization: Bearer {{auth_token}}

file: <AUDIO_DOSYASI>
